# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: advice_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'advice_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x64vice_service.proto\x12\x0emeetingadvisor\"\x1d\n\nTranscript\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x19\n\x06\x41\x64vice\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2V\n\x0eMeetingAdvisor\x12\x44\n\x0eGenerateAdvice\x12\x1a.meetingadvisor.Transcript\x1a\x16.meetingadvisor.Adviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'advice_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIPT']._serialized_start=40
  _globals['_TRANSCRIPT']._serialized_end=69
  _globals['_ADVICE']._serialized_start=71
  _globals['_ADVICE']._serialized_end=96
  _globals['_MEETINGADVISOR']._serialized_start=98
  _globals['_MEETINGADVISOR']._serialized_end=184
# @@protoc_insertion_point(module_scope)
